# This workflow will run API tests using newman and create artifacts through Actions

name: CI NewmanXActions

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: 'Confirm to Run manually'
        required: true

# Workflow run contains single job called "newman_run"
jobs:
  newman_run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${{ github.event.before }}"  
      
     
      - name: Rollback Release
        #if: failure()
        run: |
          #git reset --hard "${{ github.event.before }}"
          #git reset --hard "5f3d462"
          #git revert HEAD~1..HEAD
          git revert 64651a6d96704dd0372fbcd8331f53b42b08f847

#         uses: author/action-rollback@stable 
#         with:
#           # Using a known release ID
#           release_id: ${{ github.event.before }}
# #           #  If the release does not exist but the tag does, setting this to true will remove the tag.
# #           delete_orphan_tag: true
#         env:
#           GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
      
#       - name: Rollback Release
#         if: failure()
# #         uses: exions/undo-push@v1
#         uses: srt32/revert@v0.0.1
#         env:
#           GITHUB_TOKEN: ${{ secrets.TOKEN }}
          
      - name: Output Run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: Results
